from django.urls import path

from book_customer import customer_views

urlpatterns = [

    path('main/', customer_views.c_home),
    path('clogin/', customer_views.customer_login),
    path('logout/', customer_views.customer_logout),
    path('creg/', customer_views.creg),
    path('cotp/', customer_views.c_otppage),
    path('cgrid/<int:id>', customer_views.grid),
    path('clist/', customer_views.list),
    path('cdetail/<int:id>', customer_views.detail),
    path('c_forgot/', customer_views.c_forgot),
    path('c_otp/', customer_views.otp),
    path('c_password/', customer_views.change_password),
    path('cprofile/', customer_views.c_profile),
    path('cart/', customer_views.cart),
    path('checkout/', customer_views.c_checkout),
    path('insert_cart/<int:id>', customer_views.insert_cart),
    path('c_delete/<int:id>', customer_views.c_delete),
    path('update_cart/<int:id>', customer_views.update_qty),
    path('search/', customer_views.autosuggest, name='pro_search'),
    path('search_product/', customer_views.search),
    path('c_orderlist/', customer_views.orderlist),
    path('ajax/load-cities/', customer_views.sort_product, name='ajax_sort_products'),
    path('ajax/load-cities1/', customer_views.sort_product1, name='ajax_sort_products1'),
    path('ajax/load-cities2/', customer_views.sort_product_list, name='ajax_sort_products2'),
    path('ajax/load-cities3/', customer_views.customer_sort_list, name='ajax_sort_products3'),
    path('cwishlist/', customer_views.c_wishlist),
    path('c_dwishlist/<int:id>', customer_views.c_dwishlist),
    path('cl_wishlist/', customer_views.cl_wishlist),
    path('c_sell/', customer_views.customer_sell_page),
    path('order_list/', customer_views.order_list),
    path('c_about/', customer_views.about_us),
    path('client_header_menu/', customer_views.load_menu),
    path('customer_book/', customer_views.customer_books),
    path('customer_list/', customer_views.customer_list),
    path('new_book/<int:id>', customer_views.New_Books),
    path('c_b/<int:id>', customer_views.cat_book),
    path('c_b1/<int:id>', customer_views.cat_book1),
    path('l_b/<int:id>', customer_views.location_book),
    path('order_success/<int:id>', customer_views.payment_success),
    path('order_success1/<int:id>', customer_views.pay_success),
    path('order_success_customer/<int:id>', customer_views.payment_success_customer),
    path('order_success_customer1/<int:id>', customer_views.payment_success_customer1),
    path('customer_book_detail/<int:id>', customer_views.customer_detail),
    path('sucs/', customer_views.success),
    path('c_checkout/', customer_views.customer_checkout),
    path('new_book1/', customer_views.New_book1),
    path('mybook/', customer_views.Mybook),
    path('c_orderdetails1/<int:id>', customer_views.show_order_detail1),
    path('order_list1/', customer_views.order_list1),
    path('feed_insert/', customer_views.insert_feedback),
    path('c_orderdetails/<int:id>', customer_views.show_order_detail),
    path('order_list/', customer_views.order_list),
    path('acceptcustomer/<int:id>', customer_views.accept_order),
    path('rejectcustomer/<int:id>', customer_views.reject_order),
    path('customer_update_pass/', customer_views.customer_update_pass),
    path('d_used_book/<int:bid>', customer_views.destroy_used_book),

]
