# Generated by Django 4.2.3 on 2023-09-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=20)),
                ('a_pincode', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=200)),
                ('b_price', models.IntegerField()),
                ('b_qty', models.IntegerField()),
                ('b_img', models.CharField(max_length=100)),
                ('b_des', models.CharField(max_length=150)),
                ('is_available', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_des', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_date', models.DateField()),
                ('o_status', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_fname', models.CharField(max_length=20)),
                ('u_lname', models.CharField(max_length=20)),
                ('u_contact', models.CharField(max_length=13)),
                ('u_address', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=50)),
                ('u_password', models.CharField(max_length=10)),
                ('is_admin', models.IntegerField(null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.area')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.book')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.user')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_des', models.CharField(max_length=150)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('od_id', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Total_amount', models.IntegerField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.book')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.user'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_date', models.CharField(max_length=10)),
                ('f_des', models.CharField(max_length=150)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.book')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('added_date', models.DateField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_admin.book')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_admin.user')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='l_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.language'),
        ),
        migrations.AddField(
            model_name='book',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_admin.sub_category'),
        ),
        migrations.AddField(
            model_name='book',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_admin.user'),
        ),
    ]
