# Generated by Django 4.2.6 on 2023-11-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_des',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_des',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='f_des',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='s_des',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.CharField(max_length=50),
        ),
    ]
