# Generated by Django 5.0.6 on 2024-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='a_name',
            field=models.CharField(max_length=100),
        ),
    ]
