# Generated by Django 5.0.6 on 2024-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0002_alter_area_a_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='a_pincode',
            field=models.IntegerField(),
        ),
    ]
