# Generated by Django 5.0.6 on 2024-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0003_alter_area_a_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_des',
            field=models.CharField(max_length=1000),
        ),
    ]
